### ISSUE TITLE
Wrong format in card number || How show CVV in card?

### ISSUE THREAD

**Issue by rminossi** [guastallaigor/vue-paycard#17]
Hello,

I'm trying to use the package, but the card number appears in the wrong format, it ends up being **** 0 ***** 6 **** 5 6 ###, with masked true, and 52920 50416 33115 6 ### with masked false.

ps: master card

Another question, is there how to display the cvv on the card?

Thankful,

![image](https://user-images.githubusercontent.com/15183921/107110578-b7b46c00-6827-11eb-85e2-23caad225efc.png)

**Comment by guastallaigor** [comment]
Hello,  I just tried your number using our Storybook and it seems to be just fine with that credit card number you are trying to use, based on our form component:

Credit card number: 5292 0504 1633 1156

**Storybook.js**

![image](https://user-images.githubusercontent.com/22016005/107128998-d99e0500-68a0-11eb-9d31-19a60cefcf80.png)

I tried typing it and copying and pasting it, both worked just fine.
But I understand your form component can be different from ours, and that it what's generating the issue.
However, the general idea and code from Vue Interactive Paycard wasn't changed, as stated in our documentation.
Could you create a reproduction link of the bug using your code?
And/or maybe give some ideas and feedback on how we can improve this component.

About the CVV, you pretty much need an input field with:
  1. An `id` that matches the string you passed on the `inputFields.cardCvv` prop;
  2. A `v-model` or `v-bind:value` that binds with the `valueFields.cardCvv` prop.
  
If you have a chance, please, look into our [form](https://github.com/guastallaigor/vue-paycard/blob/master/tests/unit/form.vue) component and our [Storybook](https://vue-paycard.netlify.app/) to see how that is currently working right now.

**Comment by diogocoutinho** [comment]
Hello, I will show my case, maybe help u.

I'm using BootstrapVue with b-form-input component, how u can see in this code:

```
<vue-paycard
	:input-fields="inputFields"
	:value-fields="form"
	:labels="cardLabels"
	is-card-number-masked
	:background-image="require('../../assets/img/background-meu-ambiente.png')"
/>
<b-form-group>
	<b-form-input
		v-mask="'####'"
		min="3"
		max="4"
		:state="inputState('cardCvv')"
		:id="inputFields.cardCvv"
		v-model="form.cardCvv"
		class="slay-input slay-input-2"
		type="tel"
		placeholder="Código CVV"
		required
		data-card-field
	></b-form-input>
	<b-form-invalid-feedback :state="inputState('cardCvv')">
		{{ (inputState('cardCvv') == false) ? erros.cardCvv[0] : '' }}
	</b-form-invalid-feedback>
</b-form-group>	
```

This work perfectly to me.
I was problem with cvv too, and i solved with `data-card-field`, I just add it.

If u don't use BootstrapVue, you can made like this:

```
<div class="card-input">
    <label for="cardCvv" class="card-input__label" aria-label="Card CVV">CVV</label>
    <input
      type="tel"
      title="CVV"
      class="card-input__input"
      v-number-only
      :id="inputFields.cardCvv"
      maxlength="4"
      :value="valueFields.cardCvv"
      @input="changeCvv"
      data-card-field
      autocomplete="off"
    />
  </div>
```
I hope that help.
And maybe in close future I make something to we can pass style objects for better customizations

Thanks @guastallaigor by the component

**Comment by guastallaigor** [comment]
Hello @diogocoutinho, sorry about the delay.
I tried your example, and it seems to be working just fine for me.

I know that the "Basic usage" right now in the documentation is really bad, but I just didn't want it to put the whole form component there (contributions and suggestions regarding documentation are welcomed).
However, the `data-card-field` attribute is necessary and it's on the documentation on the "Props" section, inside the `input-fields` description.

So, to clarify, right now your form input fields needs to have:

1. An unique `id` for each one of them as stated on the `input-fields` prop;
2. The `data-card-field` attribute.

I will leave this issue opened for a while, so if you have any questions feel free to asked below.
But for problems or specific use cases, I will need a proper reproduction link.
Thank you.
