### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by jonalxh** [guastallaigor/vue-paycard#9]
**Describe the bug**

Trying to use the component in Nuxt throws me the following error:

```
ERROR in ./node_modules/vue-paycard/src/assets/images/chip.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

**To Reproduce**
I just imported in my file:
`import { VuePaycard } from 'vue-paycard'`

in my components section I instanced the import and set the data as in your example:

```
components: {
		VuePaycard
	},
data() {
	return {
		valueFields: {
                        cardName: '',
                        cardNumber: '',
                        cardMonth: '',
                        cardYear: '',
                        cardCvv: ''
                   }
	};
}
```

The final step was instance the component in the html section:

`<vue-paycard :value-fields="valueFields" />`

Then 
**Expected behavior**
Component should be shown, but the error in thrown instead.

I've thought the problem was with Nuxt loader for png files, but nuxt includes this loader automatically and I'm using a lot of png files in my project.

**Environment:**
 - OS: Linux
 - Browser: Chrome 
 - Build environment (i.e. NodeJS): Nuxt JS, It happens in development environment (npm run dev).

**Comment by jonalxh** [comment]
My bad, for anyone with the same issue with Nuxt is just to push some rules to the build section of `nuxt.config.js`, I don't know why:

```
 build: {
    extend(config, { isDev, isClient }) {
      config.module.rules.push({
        test: /\.(ttf|eot|png|jpg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
        loader: 'file-loader'
      })
}
```

Adding png and jpg worked.

**Comment by guastallaigor** [comment]
It's definitely strange, I will look into it tomorrow.
Thank you for the heads up!
